title: David Leshchiner
logo: https://github.com/Dmando/Dmando.github.io/blob/3862f6a2c1b6657721a0d29bce6213bbecf39f94/photos/headshot_profile_march2025.JPG
show_downloads: false
theme: jekyll-theme-minimal
