title: David Leshchiner
logo: https://github.com/Dmando/Dmando.github.io/blob/978be9b92f5129633ad5d93a9180b0e98fa415d8/photos/headshot_profile_march2025.png
show_downloads: false
theme: jekyll-theme-minimal
